# Use uma imagem base do OpenJDK
FROM openjdk:17

# Define o diretório de trabalho no contêiner
WORKDIR /app/backend

# Copia todos os arquivos do diretório atual para o contêiner
COPY ./ /app/backend/

# Dá permissão de execução ao Maven Wrapper (necessário para sistemas baseados em Linux)
RUN chmod +x mvnw mvnw.cmd

# Baixa as dependências e compila o projeto
RUN ./mvnw clean package

# Comando para executar a aplicação
CMD ["./mvnw", "spring-boot:run"]
